#!/bin/bash

# colors
THICK="\033[1m"
CYAN="\033[1;36m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
RESET="\033[m"

# define
FAIL="${THICK}[ ${RED}FAIL${RESET}${THICK} ]${RESET}"
PASS="${THICK}[ ${GREEN}PASS${RESET}${THICK} ]${RESET}"


cd server
npm run lint
if [ "$?" != 0 ]; then
	printf "$FAIL Linter check failed, commit not allowed.\n"
	npm run lint:fix
	if [ "$?" != 0 ]; then
	printf "Please fix errors mannually.\n"
	fi
	printf "Quitting...\n"
	exit 1
fi

printf "$PASS Lint check passed. Committing...\n"